FROM openjdk:11-jre

ENV SWARM_VERSION={{jenkins_slave.swarm_version}}
ENV HOME {{jenkins_home_dir}}
ENV JENKINS_HOME {{jenkins_home_dir}}
ENV JENKINS_EXECUTORS {{ansible_processor_vcpus}}

# Create user & install swarm-client.jar
RUN mkdir -p ${JENKINS_HOME} \
  && chown {{jenkins_uid}}:{{jenkins_gid}} ${JENKINS_HOME} \
  && groupadd -g {{jenkins_gid}} {{jenkins_username}} \
  && useradd -d ${JENKINS_HOME} -u {{jenkins_uid}} -g {{jenkins_gid}} -m -s /bin/bash {{jenkins_username}} \
  && curl -o /bin/swarm-client.jar -SL https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/$SWARM_VERSION/swarm-client-$SWARM_VERSION.jar

RUN apt-get update \
  && apt-get install -y pipenv git vim sudo \
  && apt-get install -y --no-install-recommends apt-transport-https ca-certificates curl gnupg-agent software-properties-common \
  && curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - \
  && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
  && apt-get update && apt-get install -y --no-install-recommends docker-ce

# Change the docker group ID to the same as the host so that non-root users can access the socket via its group membership.
RUN groupmod -g {{docker_group_id}} docker

USER {{jenkins_username}}

VOLUME ${JENKINS_HOME}
WORKDIR ${JENKINS_HOME}


CMD ["sh", "-c", "java -jar /bin/swarm-client.jar -master ${JENKINS_MASTER} -username ${JENKINS_USER} -password ${JENKINS_PASS} -name ${JENKINS_NAME} -executors ${JENKINS_EXECUTORS}"]
